### PR TITLE
Don't transform points two times in presimplify

### PR DESCRIPTION
**Pull request by lukasappelhans**
I was working with a topojson, where d3.geo.bounds got abnormal results. I think the two coordinates loose precision when you transform them to absolute and then back to relative. This PR fixes the issue for me.

### CODE REVIEW

**Comment by mbostock** [comment]
This doesn’t look correct. There are two cases to consider here:

If the TopoJSON is not quantized (as in, there’s no *topology*.transform) then each pair of coordinates are floating-point values and the `absolute` and `relative` transforms are no-ops. I’m guessing the data you are using *is* quantized, so this case doesn’t apply here.

If the TopoJSON is quantized (as in, there is a *topology*.transform), then each pair of coordinates are integer values with a delta-encoding, meaning that each pair of coordinates is relative to the previous pair, if any. The `absolute` transform both converts back to floating-point space and removes the delta encoding; the `relative` transform does the reverse. Thus, **if you remove points, you can’t simply add back the original relative coordinates.**

Assuming that the TopoJSON is quantized, it’s unlikely that the level of quantization approaches the resolution of a IEEE 754 floating-point number (which can represent integers with up to 53 bits). That means it’s unlikely that converting from integer coordinates to floating-point and back again shouldn’t be lossy… but perhaps we need to use Math.round rather than bitwise floor (`| 0`)?

I really need a test case to investigate this further.

**Comment by mbostock** [comment]
Edit: Even though this fix doesn’t “look right” I still appreciate you bringing it to my attention and hope we can resolve this issue. 😄

**Comment by lukasappelhans** [comment]
Thank you for the long explanation! That was very helpful! Plus your guess about rounding vs flooring seems to be right.

You can check out the following blocks with the error and the (new) fix. The map is getting automatically projected with mercator. I use d3.geo.bounds for that, but the old code gives me a BB of [[-180, -90], [180, 90]] (it gets logged to the console).

Error: http://bl.ocks.org/lukasappelhans/967f744f80ff2209ad946570063210f4
Fixed: http://bl.ocks.org/lukasappelhans/6e393c9ee954955a8799514386bd68bb

If this sounds right to you, I will update this pull request tomorrow.

**Comment by mbostock** [comment]
Sounds good!

**Comment by lukasappelhans** [comment]
Done. :)

**Comment by mbostock** [comment]
Looks good, especially given 1f19cc381249b6b05656776cd254902f31d228f7!

**Comment by mbostock** [comment]
Merged and released as 1.6.25.

**Comment by lukasappelhans** [comment]
Awesome, thank you so much! :)

**Pull request closed without merging**
